name: transit_share
description: Community-driven real-time bus tracking app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_signin_button: ^2.0.0
  provider: ^6.0.5
  # TODO: add firebase_auth or other auth packages later

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
