name: transit_share
description: Community-driven real-time bus tracking app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_signin_button: ^2.0.0
  provider: ^6.0.5
  mapbox_gl: ^0.16.0 # This will be overridden
  socket_io_client: ^2.0.0
  permission_handler: ^12.0.1
  geolocator: ^12.0.0
  # TODO: add firebase_auth or other auth packages later

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      ref: master

flutter:
  uses-material-design: true
